version: '3.7'

services:
  api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: &api-environment
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: secret_key
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      NEW_RELIC_CONFIG_FILE: newrelic.ini
    env_file: .env
    command: newrelic-admin run-program python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
