# Generated by Django 5.1.1 on 2024-09-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_task_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
