# Generated by Django 5.1.1 on 2024-10-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_user_date_of_birth_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
